#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const readline = require("readline");
const os = require("os");

const PACKAGE_JSON = require("../package.json");

const TEMPLATE_PATH = path.join(__dirname, "..", "AGENTS.template.md");
const FRACTAL_AGENT_PATH = path.join(__dirname, "..", "opencode-agents", "fractal.md");
const TARGET_DIR = path.join(os.homedir(), ".config", "opencode");
const TARGET_PATH = path.join(TARGET_DIR, "AGENTS.md");
const AGENTS_TARGET_DIR = path.join(TARGET_DIR, "agents");
const FRACTAL_TARGET_PATH = path.join(AGENTS_TARGET_DIR, "fractal.md");
const GENERATED_MARKER = `Generated from fractal-skills v${PACKAGE_JSON.version}`;
const HELP_TEXT = `Fractal Skills OpenCode installer

Usage:
  fractal-skills install
  fractal-skills uninstall [--dry-run]
  node scripts/install.js install
  node scripts/install.js uninstall [--dry-run]

Install generates ~/.config/opencode/AGENTS.md
and installs ~/.config/opencode/agents/fractal.md.
Uninstall removes only files generated by this installer.
`;

function ask(rl, question) {
  return new Promise((resolve) => {
    rl.question(question, (answer) => resolve(answer.trim()));
  });
}

async function readNonInteractiveAnswers() {
  if (process.stdin.isTTY) {
    return [];
  }

  const chunks = [];

  for await (const chunk of process.stdin) {
    chunks.push(chunk);
  }

  return Buffer.concat(chunks)
    .toString("utf-8")
    .split(/\r?\n/)
    .map((value) => value.trim());
}

function createPrompt(queuedAnswers) {
  if (!process.stdin.isTTY) {
    let index = 0;

    return {
      ask(question) {
        process.stdout.write(question);
        const answer = queuedAnswers[index] ?? "";
        index += 1;
        return Promise.resolve(answer);
      },
      close() {},
    };
  }

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return {
    ask(question) {
      return ask(rl, question);
    },
    close() {
      rl.close();
    },
  };
}

async function confirmOverwrite(prompt, filePath) {
  const answer = await prompt.ask(`\n${filePath} already exists.\nOverwrite? [y/N] `);
  return answer.toLowerCase() === "y";
}

function stampGeneratedContent(content) {
  if (content.includes(GENERATED_MARKER)) {
    return content;
  }

  if (content.startsWith("---\n")) {
    return content.replace("---\n", `---\ngenerated_from: "${GENERATED_MARKER}"\n`);
  }

  return `<!-- ${GENERATED_MARKER} -->\n${content}`;
}

function isGeneratedByInstaller(filePath) {
  return fs.existsSync(filePath) && fs.readFileSync(filePath, "utf-8").includes(GENERATED_MARKER);
}

async function installAgentFile(prompt, srcPath, dstPath) {
  if (fs.existsSync(dstPath)) {
    const shouldOverwrite = await confirmOverwrite(prompt, dstPath);
    if (!shouldOverwrite) {
      console.log(`  Skipped: ${dstPath}`);
      return false;
    }
  }

  const content = stampGeneratedContent(fs.readFileSync(srcPath, "utf-8"));
  fs.writeFileSync(dstPath, content, "utf-8");
  console.log(`  ✓ Installed: ${dstPath}`);
  return true;
}

async function installAgents(prompt) {
  console.log("\nInstalling OpenCode fractal agent...");
  fs.mkdirSync(AGENTS_TARGET_DIR, { recursive: true });

  const written = await installAgentFile(prompt, FRACTAL_AGENT_PATH, FRACTAL_TARGET_PATH);
  console.log(`\nFractal agent: ${written ? "installed" : "skipped"}.`);
}

function validateRuntimeFiles() {
  if (!fs.existsSync(TEMPLATE_PATH)) {
    console.error("ERROR: AGENTS.template.md not found.");
    console.error("Ensure AGENTS.template.md exists in the package root.");
    process.exit(1);
  }

  if (!fs.existsSync(FRACTAL_AGENT_PATH)) {
    console.error("ERROR: opencode-agents/fractal.md not found.");
    console.error("Ensure the fractal agent definition is included with this package.");
    process.exit(1);
  }
}

function resolveCommand(argv) {
  const [command, ...flags] = argv;

  if (!command) {
    return { command: "install", dryRun: false };
  }

  if (command === "install" || command === "uninstall") {
    const unknownFlag = flags.find((flag) => flag !== "--dry-run");
    if (unknownFlag) {
      console.error(`ERROR: Unknown option '${unknownFlag}'.`);
      console.error(HELP_TEXT);
      process.exit(1);
    }

    return { command, dryRun: flags.includes("--dry-run") };
  }

  if (command === "help" || command === "--help" || command === "-h") {
    console.log(HELP_TEXT);
    process.exit(0);
  }

  console.error(`ERROR: Unknown command '${command}'.`);
  console.error(HELP_TEXT);
  process.exit(1);
}

function uninstallFile(filePath, dryRun) {
  if (!fs.existsSync(filePath)) {
    console.log(`  Missing: ${filePath}`);
    return false;
  }

  if (!isGeneratedByInstaller(filePath)) {
    console.log(`  Skipped non-generated file: ${filePath}`);
    return false;
  }

  if (dryRun) {
    console.log(`  Would remove: ${filePath}`);
    return true;
  }

  fs.unlinkSync(filePath);
  console.log(`  Removed: ${filePath}`);
  return true;
}

function uninstall(dryRun) {
  console.log(`\nUninstalling OpenCode fractal files${dryRun ? " (dry run)" : ""}...`);
  const removedAgents = uninstallFile(TARGET_PATH, dryRun);
  const removedFractal = uninstallFile(FRACTAL_TARGET_PATH, dryRun);

  if (!dryRun && fs.existsSync(AGENTS_TARGET_DIR) && fs.readdirSync(AGENTS_TARGET_DIR).length === 0) {
    fs.rmdirSync(AGENTS_TARGET_DIR);
    console.log(`  Removed empty directory: ${AGENTS_TARGET_DIR}`);
  }

  console.log(`\nUninstall complete: ${removedAgents || removedFractal ? "changes found" : "nothing removed"}.`);
}

async function main() {
  const { command, dryRun } = resolveCommand(process.argv.slice(2));

  if (command === "uninstall") {
    uninstall(dryRun);
    return;
  }

  validateRuntimeFiles();

  const template = fs.readFileSync(TEMPLATE_PATH, "utf-8");
  const prompt = createPrompt(await readNonInteractiveAnswers());

  console.log("╔══════════════════════════════════════════════╗");
  console.log("║      Fractal Skills — OpenCode Installer     ║");
  console.log("╚══════════════════════════════════════════════╝");
  console.log("");
  console.log("This script generates ~/.config/opencode/AGENTS.md");
  console.log("and installs the OpenCode fractal agent definition.");
  console.log("");

  try {
    const userName = await prompt.ask("Your name: ");
    const languages = await prompt.ask(
      "Languages you work with (e.g. Rust, TypeScript, Python): "
    );

    if (!userName || !languages) {
      console.error("\nERROR: Both name and languages are required.");
      process.exit(1);
    }

    // Apply template substitutions
    const result = stampGeneratedContent(
      template
        .replace(/\{\{USER_NAME\}\}/g, userName)
        .replace(/\{\{LANGUAGES\}\}/g, languages)
    );

    // Ensure target directory exists
    fs.mkdirSync(TARGET_DIR, { recursive: true });

    // Check if existing - prompt warning
    if (fs.existsSync(TARGET_PATH)) {
      const shouldOverwrite = await confirmOverwrite(prompt, TARGET_PATH);
      if (!shouldOverwrite) {
        console.log("\nAGENTS.md skipped. Proceeding with fractal agent installation...");
      } else {
        fs.writeFileSync(TARGET_PATH, result, "utf-8");
        console.log(`\n✓ Written: ${TARGET_PATH}`);
      }
    } else {
      fs.writeFileSync(TARGET_PATH, result, "utf-8");
      console.log(`\n✓ Written: ${TARGET_PATH}`);
    }

    await installAgents(prompt);
  } finally {
    prompt.close();
  }

  console.log("\n  Restart your coding agent session for changes to take effect.");
  process.exit(0);
}

main().catch((err) => {
  console.error("ERROR:", err.message);
  process.exit(1);
});
